let vilao = [
    {
        nome: "Ghostface",
        detalhes: "Ghostface é o nome dado ao assassino mascarado da franquia de filmes de terror Pânico. Com sua máscara de fantasma, ele aterroriza os personagens e é conhecido por seu estilo de matar brutal e calculista. o Assassino costuma ligar para suas vítimas e citar filmes de terror durante seus ataques, fazendo com que elas vivenciem momentos de terror psicológico antes de encontrar a morte. Se você é fã de filmes de terror e gosta de uma boa história com uma combinação única de suspense, terror e humor, a franquia Pânico é uma ótima opção.",
        trailer: "https://www.youtube.com/watch?v=Xlut875doho",
        tags:"panico gostface",
    },
    {
        nome: "Jeepers Creepers",
        detalhes: "O assassino Jeepers Creepers é uma entidade sobrenatural apresentada na franquia de filmes de terror Olhos famintos que assombra estradas rurais. Não se trata de um ser humano com motivações convencionais, mas sim de uma criatura antiga e malévola, que a cada 23 anos desperta durante 23 dias para poder se alimentar. Além de ser extremamente forte, ágil e capaz de realizar feitos impossíveis para um ser humano, ele possui uma capacidade de regeneração que dificulta sua eliminação e o torna uma ameaça constante para aqueles que cruzam seu caminho.",
        trailer: "https://www.youtube.com/watch?v=ayax_ErKAbs",
        tags:"olhos famintos jepers crepers",
    },
    {
        nome: "Michael Myers",
        detalhes: "O icônico Michael Myers é o vilão de Halloween, conhecido por sua implacável perseguição às suas vítimas durante a noite do Dia das Bruxas. Com sua máscara branca e inexpressiva, ele oculta suas emoções, tornando-se uma figura ainda mais enigmática e assustadora. Apesar de não ter superpoderes, Michael Myers possui uma força física excepcional, capaz de realizar feitos que desafiam as leis da natureza. Myers é mais do que apenas um assassino em série; em algumas interpretações, sugere-se até que ele seja uma encarnação do mal.",
        trailer: "https://www.youtube.com/watch?v=7cFHVoIh_KI",
        tags:"micael miers michael miers halloween helloween halowen",
    },
        
     {  nome: "Jason",
        detalhes: "Quando criança, Jason se afoga no lago do acampamento Crystal Lake enquanto os instrutores estão distraídos. A princípio, sua mãe, Pamela Voorhees, busca vingança pela sua morte, matando vários conselheiros. Com o tempo, Jason é revelado como o verdadeiro assassino, tendo sobrevivido ao afogamento. Deformado e com uma força sobre-humana, ele se torna uma lenda local, retornando ao acampamento para continuar sua matança. Ao longo dos filmes, a motivação de Jason se torna cada vez mais secundária e, apesar das diversas interpretações, a essência de Jason permanece a mesma: um assassino implacável em busca de vingança.",
        trailer: "https://www.youtube.com/watch?v=dGT2-aWLHDw",
        tags:"cristal lake crystal lake jazon",
    },
    {
        nome: "Alien",
        detalhes: "O Alien, ou Xenomorfo, é uma criatura alienígena retratada como um predador implacável e inteligente, capaz de ameaçar a existência de qualquer civilização. O Xenomorfo tem um ciclo de vida complexo e aterrorizante, que envolve a infecção de um hospedeiro para a criação de uma nova forma de vida. Na fase adulta, é uma criatura alta com um exoesqueleto negro brilhante e resistente. Possui uma cabeça alongada com uma mandíbula interna retrátil que se estende para fora para atacar, garras afiadas e uma cauda longa e pontiaguda, usada tanto para ataque quanto para equilíbrio. Além disso, seu sangue é altamente corrosivo, servindo como um mecanismo de defesa e, em alguns casos, como um ataque.Essa combinação única de características biológicas e comportamentais torna essa criatura uma máquina de matar extremamente eficiente, sendo chamada também de 'o organismo perfeito'. O monstro teve sua primeira aparição no filme Alien: O Oitavo Passageiro (1979), onde, durante uma viagem, a tripulação da nave espacial Nostromo é aterrorizada por essa criatura de comportamento furtivo e letal, usando a nave como seu território e atacando os membros da tripulação um a um para garantir a sobrevivência de sua espécie",
        trailer: "https://www.youtube.com/watch?v=nvGCVfw8QlY",
        tags:"alienigena espaço",
    },
    {
        nome: "Chucky",
        detalhes: "Chucky é o protagonista da franquia Brinquedo Assassino, que inclui diversos filmes e uma série de televisão. Ele é um boneco aparentemente inofensivo que esconde uma alma sombria e um desejo insaciável de matar.Chucky, na verdade, é a alma de Charles Lee Ray, um serial killer que transferiu sua consciência para um boneco através de um ritual de vodu antes de ser morto pela polícia. Ray se tornou Chucky, um boneco capaz de se mover e falar, com o objetivo de transferir sua alma para um corpo humano e continuar sua matança.",
        trailer: "https://www.youtube.com/watch?v=zdQmWhnK5_I",
        tags:"boneco chacky chaky",
    },
    {
        nome: "Predador",
        detalhes: "O Predador, ou Yautja, é originário da franquia de filmes de mesmo nome. É um alienígena de uma espécie avançada e altamente desenvolvida, conhecida por suas habilidades em caça e combate. O caçador intergaláctico tem uma forma humanoide, é alto e musculoso, com pele escamosa, mandíbulas estendíveis e usa uma máscara que cobre a maior parte do rosto para amplificar os sentidos e analisar suas presas. O Predador possui garras afiadas, força sobre-humana e sentidos aguçados. Utiliza sua tecnologia avançada para as caçadas, que podem incluir armas tecnológicas e dispositivos que permitem torná-lo invisível ao ambiente. A caça é a principal motivação dos Predadores. Eles buscam presas dignas para testar suas habilidades e coletar troféus. Sua busca pela caça e pela honra os torna adversários formidáveis para qualquer inimigo. Eles seguem um código de conduta e respeitam seus oponentes, preferindo caçar em condições de igualdade e evitando atacar presas indefesas ou feridas. Por manter sua honra, o Predador se tornou um vilão popular e até querido por muitos.",
        trailer: "https://www.youtube.com/watch?v=bpAc_FLxdhI",
        tags:"caçador caça",
    },
    {
        nome: "Gru",
        detalhes: "Gru é o protagonista da franquia de animação Meu Malvado Favorito. Inicialmente apresentado como um supervilão ambicioso e calculista, com um plano grandioso de roubar a Lua e dominar o mundo, ele passa por uma transformação significativa ao longo dos filmes. Especialmente após adotar as três meninas órfãs — Margo, Edith e Agnes — Gru se transforma de um vilão egoísta e ambicioso em um pai amoroso e herói. Sua personalidade se torna mais gentil e preocupada com o bem-estar de sua família e com a moralidade. Gru é um personagem complexo e cheio de nuances, que nos mostra que até mesmo os mais sombrios podem ter um coração bom.",
        trailer: "https://www.youtube.com/watch?v=c0z3Fx5p2CI",
        tags:"minion",
    },
    {
        nome: "Leatherface",
        detalhes: "Conhecido por sua aparição na franquia 'O Massacre da Serra Elétrica', Leatherface é um membro da família Sawyer, uma família de canibais que vive em uma área rural isolada do Texas. Ele é frequentemente retratado como um indivíduo tímido e infantil, mas se transforma em um assassino brutal quando usa sua máscara. Alto e forte, Leatherface é uma figura imponente e intimidante. Sua máscara de couro, feita com a pele das vítimas, oculta seu rosto e acentua seu aspecto grotesco",
        trailer: "https://youtu.be/hMI41c3STXw?si=Y-qqMP5WhR6vbr_Q",
        tags:"leterface massacre serra eletrica elétrica",
    },
    {
        nome: "Thanos",
        detalhes: "Thanos nasceu em Titã, uma lua de Saturno, como um Eterno com uma mutação genética que lhe conferiu uma aparência peculiar. Thanos desenvolveu uma obsessão pela Morte, personificada como uma entidade cósmica. Ele acredita que a única maneira de salvar o universo é eliminando metade de toda a vida existente, restaurando assim o equilíbrio e evitando a escassez de recursos. Para realizar seu plano, Thanos busca as Joias do Infinito, artefatos cósmicos de poder ilimitado que, quando unidas na Manopla do Infinito, lhe concedem controle sobre o universo.",
        trailer: "https://www.youtube.com/watch?v=DPOw2hfgCHI",
        tags:"tanos infinito vingadores",
    },
    {
        nome: "Coringa",
        detalhes: "O Coringa é o arqui-inimigo do Batman, um personagem que representa o caos, a loucura e a anarquia em sua forma mais pura. Sua aparência é a de um palhaço, com lábios vermelhos intensos, pele branca e cabelos verdes. Essa maquiagem simboliza a farsa da sociedade e a dualidade entre o riso e a dor. Suas roupas são geralmente coloridas e extravagantes, contrastando com a natureza sombria de seus crimes. O Coringa não segue um plano mestre; ele simplesmente gosta de causar caos e sofrimento. Seus crimes são muitas vezes aleatórios e cruéis, motivados por um senso de humor macabro e uma necessidade de chocar.",
        trailer: "https://www.youtube.com/watch?v=621pfj0EfIc",
        tags:"joker gotham batman",
    },
    {
        nome: "Pinguim",
        detalhes: "O Pinguim, cujo nome verdadeiro é Oswald Chesterfield Cobblepot, tem uma aparência inspirada em pinguins, como o próprio nome sugere. Ele usa um fraque elegante, um monóculo e um guarda-chuva como arma. Apesar de sua aparência caricata, o Pinguim é um criminoso inteligente e astuto. Ele é um estrategista habilidoso e um excelente manipulador, capaz de construir um império criminoso em Gotham City.",
        trailer: "https://www.youtube.com/watch?v=DPwSRV1XFyM",
        tags:"gotham batman pinguin",
    },
    {
        nome: "Duende Verde",
        detalhes: "O Duende Verde é o alter ego de Norman Osborn e é conhecido como o arqui-inimigo do Homem-Aranha. Norman Osborn era um empresário bem-sucedido e dono da Oscorp Industries. No entanto, após um experimento científico malsucedido, ele se transformou no Duende Verde, um ser instável e psicótico. Sua figura é marcada pela loucura, pela obsessão e por um visual distintivo, que inclui uma máscara verde e um planador. Apesar de sua insanidade, Norman é um gênio científico e possui acesso aos recursos da Oscorp, o que o torna um adversário formidável para o Homem-Aranha.",
        trailer: "https://www.youtube.com/watch?v=_yhFofFZGcc",
        tags:"homem aranha",
    },
    {
        nome: "Freddy Krueger",
        detalhes: "Freddy Krueger é um dos vilões mais aterrorizantes do cinema, conhecido por atormentar suas vítimas em seus piores pesadelos. Com sua aparência desfigurada, rosto queimado, luva com garras e sua risada macabra, ele se tornou um símbolo do terror psicológico. Freddy era um assassino de crianças em Springwood, Ohio, onde foi queimado vivo pelos pais de suas vítimas em retaliação. Após sua morte, Freddy retornou como um espírito maligno, capaz de invadir os sonhos das crianças de Springwood e matá-las enquanto dormiam. A única maneira de escapar de Freddy era permanecer acordado, o que levou a uma série de mortes horríveis e a um clima de terror constante na cidade.",
        trailer: "https://www.youtube.com/watch?v=HHNMjwYPlvY",
        tags:"fredy kruger fred fredi",
    },
    {
        nome: "Hannibal",
        detalhes: "Longe de ser um monstro irracional, Hannibal Lecter é um psiquiatra brilhante, um gourmet sofisticado e um assassino em série com um apetite peculiar. Sua característica mais marcante é o canibalismo, mas isso não se trata apenas de um ato de violência aleatória. Para Lecter, a carne humana é uma iguaria, e ele escolhe suas vítimas com cuidado, apreciando a experiência gastronômica. Lecter é um personagem complexo e fascinante que desafia as convenções do gênero de terror. Ele não é apenas um monstro, mas um ser humano com uma mente brilhante e uma personalidade perturbadora. Sua história nos convida a questionar a natureza do bem e do mal e a explorar os limites da mente humana.",
        trailer: "https://www.youtube.com/watch?v=l2Z0i0-zht8",
        tags:"hanibal haniball ",
    },
    {
        nome: "Cruella de Vil",
        detalhes: "Conhecida por sua obsessão por peles de animais, especialmente as dos dálmatas, Cruella de Vil é a antagonista principal da história de 101 Dálmatas. Sua personalidade é marcada pelo exagero, com um estilo de vida luxuoso e extravagante. Seus trajes são sempre chamativos, com um gosto peculiar por preto e branco. Ela se tornou um símbolo da vilania feminina, representando a vaidade, a crueldade e a obsessão materialista. De Vil é mais do que uma vilã de desenho animado; ela é um símbolo da superficialidade, da crueldade e da obsessão pela aparência. Sua história nos alerta sobre os perigos da vaidade.",
        trailer: "https://www.youtube.com/watch?v=p78Y5-zS3kY",
        tags:"cruela dalmatas disney",
    },
    {
        nome: "Malévola",
        detalhes: "Malévola é uma personagem da Disney, originalmente apresentada como a vilã do clássico 'A Bela Adormecida'. Antes de se tornar a vilã que conhecemos, Malévola era a poderosa fada protetora dos Moors, uma floresta mágica. No entanto, uma profunda traição amorosa a transformou em uma criatura amarga e vingativa, levando-a a amaldiçoar a filha de seu antigo amor.Com seu par de chifres altos e curvados que adornam sua cabeça, trajes geralmente de um negro profundo e sua postura majestosa e ameaçadora, Malévola reflete sua natureza sombria e misteriosa. Ela possui poderes mágicos, incluindo a capacidade de controlar os elementos, lançar feitiços e se transformar em um dragão. Além disso, é uma guerreira habilidosa, e sua presença imponente e seus poderes a tornam uma figura intimidante, capaz de inspirar tanto medo quanto respeito. Malévola se tornou um símbolo de empoderamento feminino, representando uma mulher forte, independente e capaz de se defender",
        trailer: "https://www.youtube.com/watch?v=Uqg12lAsydY",
        tags:"malevola disney",
    },
    {
        nome: "Pennywise",
        detalhes: "O palhaço dançarino é o antagonista principal da história de Stephen King, It: A Coisa. Nela, um grupo de crianças se une para enfrentar essa criatura aterrorizante e, por fim, derrotá-la. Pennywise é uma entidade sobrenatural e aterrorizante que pode assumir a forma de qualquer coisa que cause medo em suas vítimas; sua aparência muda dependendo de quem ele está tentando atrair ou assustar. Pennywise é uma entidade antiga que se alimenta do medo dos seres humanos. Ele dorme por longos períodos e acorda a cada 27 anos para caçar crianças em Derry, Maine.",
        trailer: "https://www.youtube.com/watch?v=dD264ZjfKlk",
        tags:"penywise peniwyse penywyse palhaço it palhaco",
    },
    {
        nome: "Darth Vader",
        detalhes: "Darth Vader, também conhecido como Anakin Skywalker, é o principal antagonista da saga Star Wars. Originalmente um jovem Jedi com um grande potencial na Força, Anakin se deixou corromper pelo lado sombrio e se tornou um dos vilões mais temidos da galáxia. Reconhecido por sua imponente armadura negra, capacete com visor vermelho e respiração rouca, resultado de graves feridas sofridas durante um duelo com Obi-Wan Kenobi, Vader é uma figura marcante. Sob a máscara, ele esconde um homem atormentado pela perda, pela culpa e pela raiva. Sua busca por poder e vingança o levou a se tornar um servo do Imperador Palpatine, mas ele ainda carrega resquícios de sua antiga humanidade.",
        trailer: "https://www.youtube.com/watch?v=Q8b09bE1iGQ",
        tags:"dart star wars",
    },
    {
        nome: "Art",
        detalhes: "Protagonista da franquia Terrifier, Art é uma personificação do caos e da violência, com uma estética que o torna inconfundivelmente aterrorizante. Ele usa uma maquiagem branca e pálida, lábios pintados de preto e dentes afiados que lembram mais garras do que dentes humanos. Art é quase silencioso e não possui diálogos; sua comunicação se dá através de gestos e expressões faciais, o que o torna ainda mais enigmático e assustador. Seus atos são impulsionados por uma sede insaciável de violência e destruição, e ele parece se divertir com o sofrimento de suas vítimas. A falta de uma história de fundo completa para Art aumenta o mistério em torno do personagem, permitindo que a imaginação do público preencha as lacunas e tornando-o ainda mais assustador.",
        trailer: "https://www.youtube.com/watch?v=heoFJLF-8uQ",
        tags:"terrifier terifier palhaço",
    },
];
